# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wgtwo/auth/v0/operatortokens.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wgtwo/auth/v0/operatortokens.proto',
  package='wgtwo.auth.v0',
  syntax='proto3',
  serialized_options=b'\n\025com.wgtwo.api.auth.v0B\023OperatorTokensProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"wgtwo/auth/v0/operatortokens.proto\x12\rwgtwo.auth.v0\"H\n\x15OperatorTokenMetadata\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06rights\x18\x03 \x03(\tB,\n\x15\x63om.wgtwo.api.auth.v0B\x13OperatorTokensProtob\x06proto3'
)




_OPERATORTOKENMETADATA = _descriptor.Descriptor(
  name='OperatorTokenMetadata',
  full_name='wgtwo.auth.v0.OperatorTokenMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='wgtwo.auth.v0.OperatorTokenMetadata.client_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='wgtwo.auth.v0.OperatorTokenMetadata.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rights', full_name='wgtwo.auth.v0.OperatorTokenMetadata.rights', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=125,
)

DESCRIPTOR.message_types_by_name['OperatorTokenMetadata'] = _OPERATORTOKENMETADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OperatorTokenMetadata = _reflection.GeneratedProtocolMessageType('OperatorTokenMetadata', (_message.Message,), {
  'DESCRIPTOR' : _OPERATORTOKENMETADATA,
  '__module__' : 'wgtwo.auth.v0.operatortokens_pb2'
  # @@protoc_insertion_point(class_scope:wgtwo.auth.v0.OperatorTokenMetadata)
  })
_sym_db.RegisterMessage(OperatorTokenMetadata)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
