# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wgtwo/auth/v0/rights.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wgtwo/auth/v0/rights.proto',
  package='wgtwo.auth.v0',
  syntax='proto3',
  serialized_options=b'\n\025com.wgtwo.api.auth.v0B\013RightsProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1awgtwo/auth/v0/rights.proto\x12\rwgtwo.auth.v0\"\x13\n\x11ListRightsRequest\"$\n\x12ListRightsResponse\x12\x0e\n\x06rights\x18\x01 \x03(\t\"\'\n\x15\x43heckExpansionRequest\x12\x0e\n\x06rights\x18\x01 \x03(\t\"(\n\x16\x43heckExpansionResponse\x12\x0e\n\x06rights\x18\x01 \x03(\t2\xbe\x01\n\x0cRightService\x12M\n\x04List\x12 .wgtwo.auth.v0.ListRightsRequest\x1a!.wgtwo.auth.v0.ListRightsResponse\"\x00\x12_\n\x0e\x43heckExpansion\x12$.wgtwo.auth.v0.CheckExpansionRequest\x1a%.wgtwo.auth.v0.CheckExpansionResponse\"\x00\x42$\n\x15\x63om.wgtwo.api.auth.v0B\x0bRightsProtob\x06proto3'
)




_LISTRIGHTSREQUEST = _descriptor.Descriptor(
  name='ListRightsRequest',
  full_name='wgtwo.auth.v0.ListRightsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=64,
)


_LISTRIGHTSRESPONSE = _descriptor.Descriptor(
  name='ListRightsResponse',
  full_name='wgtwo.auth.v0.ListRightsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rights', full_name='wgtwo.auth.v0.ListRightsResponse.rights', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=102,
)


_CHECKEXPANSIONREQUEST = _descriptor.Descriptor(
  name='CheckExpansionRequest',
  full_name='wgtwo.auth.v0.CheckExpansionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rights', full_name='wgtwo.auth.v0.CheckExpansionRequest.rights', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=143,
)


_CHECKEXPANSIONRESPONSE = _descriptor.Descriptor(
  name='CheckExpansionResponse',
  full_name='wgtwo.auth.v0.CheckExpansionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rights', full_name='wgtwo.auth.v0.CheckExpansionResponse.rights', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=185,
)

DESCRIPTOR.message_types_by_name['ListRightsRequest'] = _LISTRIGHTSREQUEST
DESCRIPTOR.message_types_by_name['ListRightsResponse'] = _LISTRIGHTSRESPONSE
DESCRIPTOR.message_types_by_name['CheckExpansionRequest'] = _CHECKEXPANSIONREQUEST
DESCRIPTOR.message_types_by_name['CheckExpansionResponse'] = _CHECKEXPANSIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListRightsRequest = _reflection.GeneratedProtocolMessageType('ListRightsRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTRIGHTSREQUEST,
  '__module__' : 'wgtwo.auth.v0.rights_pb2'
  # @@protoc_insertion_point(class_scope:wgtwo.auth.v0.ListRightsRequest)
  })
_sym_db.RegisterMessage(ListRightsRequest)

ListRightsResponse = _reflection.GeneratedProtocolMessageType('ListRightsResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTRIGHTSRESPONSE,
  '__module__' : 'wgtwo.auth.v0.rights_pb2'
  # @@protoc_insertion_point(class_scope:wgtwo.auth.v0.ListRightsResponse)
  })
_sym_db.RegisterMessage(ListRightsResponse)

CheckExpansionRequest = _reflection.GeneratedProtocolMessageType('CheckExpansionRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKEXPANSIONREQUEST,
  '__module__' : 'wgtwo.auth.v0.rights_pb2'
  # @@protoc_insertion_point(class_scope:wgtwo.auth.v0.CheckExpansionRequest)
  })
_sym_db.RegisterMessage(CheckExpansionRequest)

CheckExpansionResponse = _reflection.GeneratedProtocolMessageType('CheckExpansionResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHECKEXPANSIONRESPONSE,
  '__module__' : 'wgtwo.auth.v0.rights_pb2'
  # @@protoc_insertion_point(class_scope:wgtwo.auth.v0.CheckExpansionResponse)
  })
_sym_db.RegisterMessage(CheckExpansionResponse)


DESCRIPTOR._options = None

_RIGHTSERVICE = _descriptor.ServiceDescriptor(
  name='RightService',
  full_name='wgtwo.auth.v0.RightService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=188,
  serialized_end=378,
  methods=[
  _descriptor.MethodDescriptor(
    name='List',
    full_name='wgtwo.auth.v0.RightService.List',
    index=0,
    containing_service=None,
    input_type=_LISTRIGHTSREQUEST,
    output_type=_LISTRIGHTSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CheckExpansion',
    full_name='wgtwo.auth.v0.RightService.CheckExpansion',
    index=1,
    containing_service=None,
    input_type=_CHECKEXPANSIONREQUEST,
    output_type=_CHECKEXPANSIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RIGHTSERVICE)

DESCRIPTOR.services_by_name['RightService'] = _RIGHTSERVICE

# @@protoc_insertion_point(module_scope)
