# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from wgtwo.auth.v0 import rights_pb2 as wgtwo_dot_auth_dot_v0_dot_rights__pb2


class RightServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/wgtwo.auth.v0.RightService/List',
                request_serializer=wgtwo_dot_auth_dot_v0_dot_rights__pb2.ListRightsRequest.SerializeToString,
                response_deserializer=wgtwo_dot_auth_dot_v0_dot_rights__pb2.ListRightsResponse.FromString,
                )
        self.CheckExpansion = channel.unary_unary(
                '/wgtwo.auth.v0.RightService/CheckExpansion',
                request_serializer=wgtwo_dot_auth_dot_v0_dot_rights__pb2.CheckExpansionRequest.SerializeToString,
                response_deserializer=wgtwo_dot_auth_dot_v0_dot_rights__pb2.CheckExpansionResponse.FromString,
                )


class RightServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckExpansion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RightServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=wgtwo_dot_auth_dot_v0_dot_rights__pb2.ListRightsRequest.FromString,
                    response_serializer=wgtwo_dot_auth_dot_v0_dot_rights__pb2.ListRightsResponse.SerializeToString,
            ),
            'CheckExpansion': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckExpansion,
                    request_deserializer=wgtwo_dot_auth_dot_v0_dot_rights__pb2.CheckExpansionRequest.FromString,
                    response_serializer=wgtwo_dot_auth_dot_v0_dot_rights__pb2.CheckExpansionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wgtwo.auth.v0.RightService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RightService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wgtwo.auth.v0.RightService/List',
            wgtwo_dot_auth_dot_v0_dot_rights__pb2.ListRightsRequest.SerializeToString,
            wgtwo_dot_auth_dot_v0_dot_rights__pb2.ListRightsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckExpansion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wgtwo.auth.v0.RightService/CheckExpansion',
            wgtwo_dot_auth_dot_v0_dot_rights__pb2.CheckExpansionRequest.SerializeToString,
            wgtwo_dot_auth_dot_v0_dot_rights__pb2.CheckExpansionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
