# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from wgtwo.auth.v0 import usertokens_pb2 as wgtwo_dot_auth_dot_v0_dot_usertokens__pb2


class UserTokenServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/wgtwo.auth.v0.UserTokenService/Create',
                request_serializer=wgtwo_dot_auth_dot_v0_dot_usertokens__pb2.CreateUserTokenRequest.SerializeToString,
                response_deserializer=wgtwo_dot_auth_dot_v0_dot_usertokens__pb2.CreateUserTokenResponse.FromString,
                )
        self.Get = channel.unary_unary(
                '/wgtwo.auth.v0.UserTokenService/Get',
                request_serializer=wgtwo_dot_auth_dot_v0_dot_usertokens__pb2.GetUserTokenRequest.SerializeToString,
                response_deserializer=wgtwo_dot_auth_dot_v0_dot_usertokens__pb2.GetUserTokenResponse.FromString,
                )
        self.List = channel.unary_unary(
                '/wgtwo.auth.v0.UserTokenService/List',
                request_serializer=wgtwo_dot_auth_dot_v0_dot_usertokens__pb2.ListUserTokenRequest.SerializeToString,
                response_deserializer=wgtwo_dot_auth_dot_v0_dot_usertokens__pb2.ListUserTokenResponse.FromString,
                )
        self.Revoke = channel.unary_unary(
                '/wgtwo.auth.v0.UserTokenService/Revoke',
                request_serializer=wgtwo_dot_auth_dot_v0_dot_usertokens__pb2.RevokeUserTokenRequest.SerializeToString,
                response_deserializer=wgtwo_dot_auth_dot_v0_dot_usertokens__pb2.RevokeUserTokenResponse.FromString,
                )


class UserTokenServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Revoke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserTokenServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=wgtwo_dot_auth_dot_v0_dot_usertokens__pb2.CreateUserTokenRequest.FromString,
                    response_serializer=wgtwo_dot_auth_dot_v0_dot_usertokens__pb2.CreateUserTokenResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=wgtwo_dot_auth_dot_v0_dot_usertokens__pb2.GetUserTokenRequest.FromString,
                    response_serializer=wgtwo_dot_auth_dot_v0_dot_usertokens__pb2.GetUserTokenResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=wgtwo_dot_auth_dot_v0_dot_usertokens__pb2.ListUserTokenRequest.FromString,
                    response_serializer=wgtwo_dot_auth_dot_v0_dot_usertokens__pb2.ListUserTokenResponse.SerializeToString,
            ),
            'Revoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Revoke,
                    request_deserializer=wgtwo_dot_auth_dot_v0_dot_usertokens__pb2.RevokeUserTokenRequest.FromString,
                    response_serializer=wgtwo_dot_auth_dot_v0_dot_usertokens__pb2.RevokeUserTokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wgtwo.auth.v0.UserTokenService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserTokenService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wgtwo.auth.v0.UserTokenService/Create',
            wgtwo_dot_auth_dot_v0_dot_usertokens__pb2.CreateUserTokenRequest.SerializeToString,
            wgtwo_dot_auth_dot_v0_dot_usertokens__pb2.CreateUserTokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wgtwo.auth.v0.UserTokenService/Get',
            wgtwo_dot_auth_dot_v0_dot_usertokens__pb2.GetUserTokenRequest.SerializeToString,
            wgtwo_dot_auth_dot_v0_dot_usertokens__pb2.GetUserTokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wgtwo.auth.v0.UserTokenService/List',
            wgtwo_dot_auth_dot_v0_dot_usertokens__pb2.ListUserTokenRequest.SerializeToString,
            wgtwo_dot_auth_dot_v0_dot_usertokens__pb2.ListUserTokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Revoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wgtwo.auth.v0.UserTokenService/Revoke',
            wgtwo_dot_auth_dot_v0_dot_usertokens__pb2.RevokeUserTokenRequest.SerializeToString,
            wgtwo_dot_auth_dot_v0_dot_usertokens__pb2.RevokeUserTokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
