# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wgtwo/common/v0/phonenumber.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wgtwo/common/v0/phonenumber.proto',
  package='wgtwo.common.v0',
  syntax='proto3',
  serialized_options=b'\n\027com.wgtwo.api.common.v0B\020PhoneNumberProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!wgtwo/common/v0/phonenumber.proto\x12\x0fwgtwo.common.v0\"\x1b\n\x0bPhoneNumber\x12\x0c\n\x04\x65\x31\x36\x34\x18\x01 \x01(\t\"\"\n\x0bTextAddress\x12\x13\n\x0btextAddress\x18\x01 \x01(\t\"2\n\x13NationalPhoneNumber\x12\x1b\n\x13nationalPhoneNumber\x18\x01 \x01(\tB+\n\x17\x63om.wgtwo.api.common.v0B\x10PhoneNumberProtob\x06proto3'
)




_PHONENUMBER = _descriptor.Descriptor(
  name='PhoneNumber',
  full_name='wgtwo.common.v0.PhoneNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='e164', full_name='wgtwo.common.v0.PhoneNumber.e164', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=81,
)


_TEXTADDRESS = _descriptor.Descriptor(
  name='TextAddress',
  full_name='wgtwo.common.v0.TextAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='textAddress', full_name='wgtwo.common.v0.TextAddress.textAddress', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=117,
)


_NATIONALPHONENUMBER = _descriptor.Descriptor(
  name='NationalPhoneNumber',
  full_name='wgtwo.common.v0.NationalPhoneNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nationalPhoneNumber', full_name='wgtwo.common.v0.NationalPhoneNumber.nationalPhoneNumber', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=169,
)

DESCRIPTOR.message_types_by_name['PhoneNumber'] = _PHONENUMBER
DESCRIPTOR.message_types_by_name['TextAddress'] = _TEXTADDRESS
DESCRIPTOR.message_types_by_name['NationalPhoneNumber'] = _NATIONALPHONENUMBER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PhoneNumber = _reflection.GeneratedProtocolMessageType('PhoneNumber', (_message.Message,), {
  'DESCRIPTOR' : _PHONENUMBER,
  '__module__' : 'wgtwo.common.v0.phonenumber_pb2'
  # @@protoc_insertion_point(class_scope:wgtwo.common.v0.PhoneNumber)
  })
_sym_db.RegisterMessage(PhoneNumber)

TextAddress = _reflection.GeneratedProtocolMessageType('TextAddress', (_message.Message,), {
  'DESCRIPTOR' : _TEXTADDRESS,
  '__module__' : 'wgtwo.common.v0.phonenumber_pb2'
  # @@protoc_insertion_point(class_scope:wgtwo.common.v0.TextAddress)
  })
_sym_db.RegisterMessage(TextAddress)

NationalPhoneNumber = _reflection.GeneratedProtocolMessageType('NationalPhoneNumber', (_message.Message,), {
  'DESCRIPTOR' : _NATIONALPHONENUMBER,
  '__module__' : 'wgtwo.common.v0.phonenumber_pb2'
  # @@protoc_insertion_point(class_scope:wgtwo.common.v0.NationalPhoneNumber)
  })
_sym_db.RegisterMessage(NationalPhoneNumber)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
